openapi: 3.0.3
info:
  title: Oficina II - API Almoxarifado
  version: 1.0.0
  description: API para controle de almoxarifado (itens, fornecedores, busca)
paths:
  /api/fornecedores/:
    get:
      operationId: fornecedores_list
      parameters:
      - name: ordering
        required: false
        in: query
        description: Qual campo usar ao ordenar os resultados.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: Um termo de busca.
        schema:
          type: string
      tags:
      - fornecedores
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fornecedor'
          description: ''
    post:
      operationId: fornecedores_create
      tags:
      - fornecedores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Fornecedor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Fornecedor'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
          description: ''
  /api/fornecedores/{id}/:
    get:
      operationId: fornecedores_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Fornecedor.
        required: true
      tags:
      - fornecedores
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
          description: ''
    put:
      operationId: fornecedores_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Fornecedor.
        required: true
      tags:
      - fornecedores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fornecedor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Fornecedor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Fornecedor'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
          description: ''
    patch:
      operationId: fornecedores_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Fornecedor.
        required: true
      tags:
      - fornecedores
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedFornecedor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedFornecedor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedFornecedor'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fornecedor'
          description: ''
    delete:
      operationId: fornecedores_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este Fornecedor.
        required: true
      tags:
      - fornecedores
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/items/:
    get:
      operationId: items_list
      parameters:
      - in: query
        name: fornecedor
        schema:
          type: integer
      - in: query
        name: localizacao
        schema:
          type: string
      - name: ordering
        required: false
        in: query
        description: Qual campo usar ao ordenar os resultados.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: Um termo de busca.
        schema:
          type: string
      - in: query
        name: sku
        schema:
          type: string
      tags:
      - items
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
          description: ''
    post:
      operationId: items_create
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
  /api/items/{id}/:
    get:
      operationId: items_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este item.
        required: true
      tags:
      - items
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
    put:
      operationId: items_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este item.
        required: true
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
    patch:
      operationId: items_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este item.
        required: true
      tags:
      - items
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedItem'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
    delete:
      operationId: items_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Um valor inteiro único que identifica este item.
        required: true
      tags:
      - items
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Fornecedor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 255
        contato:
          type: string
          maxLength: 255
      required:
      - id
      - nome
    Item:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sku:
          type: string
          maxLength: 64
        nome:
          type: string
          maxLength: 255
        descricao:
          type: string
        quantidade:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        localizacao:
          type: string
          maxLength: 128
        fornecedor:
          allOf:
          - $ref: '#/components/schemas/Fornecedor'
          readOnly: true
        fornecedor_id:
          type: integer
          writeOnly: true
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - fornecedor
      - id
      - nome
      - sku
      - updated_at
    PatchedFornecedor:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        nome:
          type: string
          maxLength: 255
        contato:
          type: string
          maxLength: 255
    PatchedItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sku:
          type: string
          maxLength: 64
        nome:
          type: string
          maxLength: 255
        descricao:
          type: string
        quantidade:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        localizacao:
          type: string
          maxLength: 128
        fornecedor:
          allOf:
          - $ref: '#/components/schemas/Fornecedor'
          readOnly: true
        fornecedor_id:
          type: integer
          writeOnly: true
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
